import { AccessReview, AccessStats } from "@/types/access";

export const accessReviews: AccessReview[] = [
  {
    id: "AR-001",
    userId: "USR-001",
    userName: "Sarah Chen",
    userEmail: "sarah.chen@company.com",
    department: "Engineering",
    resource: "AWS Production Account",
    resourceType: "Cloud Service",
    accessLevel: "Admin",
    grantedDate: "2025-06-15",
    lastReviewDate: "2026-01-15",
    nextReviewDate: "2026-04-15",
    status: "Approved",
    reviewer: "Michael Torres",
    justification: "Required for infrastructure management duties",
    riskLevel: "High",
  },
  {
    id: "AR-002",
    userId: "USR-002",
    userName: "Michael Torres",
    userEmail: "michael.torres@company.com",
    department: "Security",
    resource: "GitHub Organization",
    resourceType: "Repository",
    accessLevel: "Owner",
    grantedDate: "2025-03-01",
    lastReviewDate: "2026-01-20",
    nextReviewDate: "2026-04-20",
    status: "Approved",
    reviewer: "Jennifer Wu",
    justification: "Security team lead - requires full access for security reviews",
    riskLevel: "High",
  },
  {
    id: "AR-003",
    userId: "USR-003",
    userName: "Jennifer Wu",
    userEmail: "jennifer.wu@company.com",
    department: "Compliance",
    resource: "PostgreSQL Production DB",
    resourceType: "Database",
    accessLevel: "Read",
    grantedDate: "2025-09-10",
    lastReviewDate: "2026-01-10",
    nextReviewDate: "2026-04-10",
    status: "Approved",
    reviewer: "David Kim",
    justification: "Compliance reporting and audit queries",
    riskLevel: "Medium",
  },
  {
    id: "AR-004",
    userId: "USR-004",
    userName: "Alex Johnson",
    userEmail: "alex.johnson@company.com",
    department: "Engineering",
    resource: "Kubernetes Cluster",
    resourceType: "Server",
    accessLevel: "Admin",
    grantedDate: "2025-07-20",
    lastReviewDate: "2025-10-20",
    nextReviewDate: "2026-01-20",
    status: "Pending",
    reviewer: "Sarah Chen",
    riskLevel: "Critical",
  },
  {
    id: "AR-005",
    userId: "USR-005",
    userName: "David Kim",
    userEmail: "david.kim@company.com",
    department: "DevOps",
    resource: "Datadog",
    resourceType: "Application",
    accessLevel: "Admin",
    grantedDate: "2025-04-05",
    lastReviewDate: "2026-01-25",
    nextReviewDate: "2026-04-25",
    status: "Approved",
    reviewer: "Michael Torres",
    justification: "Monitoring and alerting management",
    riskLevel: "Medium",
  },
  {
    id: "AR-006",
    userId: "USR-006",
    userName: "Emily Martinez",
    userEmail: "emily.martinez@company.com",
    department: "Product",
    resource: "Stripe Dashboard",
    resourceType: "Application",
    accessLevel: "Read",
    grantedDate: "2025-11-01",
    lastReviewDate: "2026-01-28",
    nextReviewDate: "2026-04-28",
    status: "Approved",
    reviewer: "Jennifer Wu",
    justification: "Product analytics and revenue reporting",
    riskLevel: "Low",
  },
  {
    id: "AR-007",
    userId: "USR-007",
    userName: "James Wilson",
    userEmail: "james.wilson@company.com",
    department: "Engineering",
    resource: "AWS Production Account",
    resourceType: "Cloud Service",
    accessLevel: "Write",
    grantedDate: "2025-08-15",
    lastReviewDate: "2025-11-15",
    nextReviewDate: "2026-02-15",
    status: "Pending",
    reviewer: "Sarah Chen",
    riskLevel: "High",
  },
  {
    id: "AR-008",
    userId: "USR-008",
    userName: "Lisa Thompson",
    userEmail: "lisa.thompson@company.com",
    department: "HR",
    resource: "BambooHR",
    resourceType: "Application",
    accessLevel: "Admin",
    grantedDate: "2025-01-10",
    lastReviewDate: "2026-01-10",
    nextReviewDate: "2026-04-10",
    status: "Approved",
    reviewer: "Michael Torres",
    justification: "HR system administration",
    riskLevel: "Medium",
  },
  {
    id: "AR-009",
    userId: "USR-009",
    userName: "Robert Garcia",
    userEmail: "robert.garcia@company.com",
    department: "Finance",
    resource: "QuickBooks",
    resourceType: "Application",
    accessLevel: "Admin",
    grantedDate: "2025-02-20",
    lastReviewDate: "2025-08-20",
    nextReviewDate: "2025-11-20",
    status: "Expired",
    reviewer: "Jennifer Wu",
    riskLevel: "High",
  },
  {
    id: "AR-010",
    userId: "USR-010",
    userName: "Amanda Lee",
    userEmail: "amanda.lee@company.com",
    department: "Marketing",
    resource: "HubSpot",
    resourceType: "Application",
    accessLevel: "Write",
    grantedDate: "2025-05-01",
    lastReviewDate: "2026-01-30",
    nextReviewDate: "2026-04-30",
    status: "Approved",
    reviewer: "David Kim",
    justification: "Marketing automation management",
    riskLevel: "Low",
  },
  {
    id: "AR-011",
    userId: "USR-003",
    userName: "Jennifer Wu",
    userEmail: "jennifer.wu@company.com",
    department: "Compliance",
    resource: "Slack Enterprise",
    resourceType: "Application",
    accessLevel: "Admin",
    grantedDate: "2025-06-01",
    lastReviewDate: "2025-09-01",
    nextReviewDate: "2025-12-01",
    status: "Pending",
    reviewer: "Michael Torres",
    riskLevel: "Medium",
  },
  {
    id: "AR-012",
    userId: "USR-012",
    userName: "Chris Brown",
    userEmail: "chris.brown@company.com",
    department: "Engineering",
    resource: "MongoDB Atlas",
    resourceType: "Database",
    accessLevel: "Write",
    grantedDate: "2025-10-15",
    lastReviewDate: "2026-01-15",
    nextReviewDate: "2026-04-15",
    status: "Approved",
    reviewer: "Sarah Chen",
    justification: "Backend development database access",
    riskLevel: "Medium",
  },
  {
    id: "AR-013",
    userId: "USR-004",
    userName: "Alex Johnson",
    userEmail: "alex.johnson@company.com",
    department: "Engineering",
    resource: "Okta Admin Console",
    resourceType: "Application",
    accessLevel: "Admin",
    grantedDate: "2025-04-01",
    lastReviewDate: "2025-07-01",
    nextReviewDate: "2025-10-01",
    status: "Revoked",
    reviewer: "Michael Torres",
    justification: "Access revoked - role change",
    riskLevel: "Critical",
  },
  {
    id: "AR-014",
    userId: "USR-014",
    userName: "Nicole Adams",
    userEmail: "nicole.adams@company.com",
    department: "Support",
    resource: "Zendesk",
    resourceType: "Application",
    accessLevel: "Write",
    grantedDate: "2025-09-01",
    lastReviewDate: "2026-01-25",
    nextReviewDate: "2026-04-25",
    status: "Approved",
    reviewer: "Jennifer Wu",
    justification: "Customer support ticket management",
    riskLevel: "Low",
  },
  {
    id: "AR-015",
    userId: "USR-001",
    userName: "Sarah Chen",
    userEmail: "sarah.chen@company.com",
    department: "Engineering",
    resource: "Terraform Cloud",
    resourceType: "Application",
    accessLevel: "Owner",
    grantedDate: "2025-03-15",
    lastReviewDate: "2026-01-15",
    nextReviewDate: "2026-04-15",
    status: "Approved",
    reviewer: "Michael Torres",
    justification: "Infrastructure as code management",
    riskLevel: "Critical",
  },
];

export const accessStats: AccessStats = {
  totalAccessRights: accessReviews.length,
  pendingReviews: accessReviews.filter((r) => r.status === "Pending").length,
  approvedThisMonth: accessReviews.filter(
    (r) => r.status === "Approved" && r.lastReviewDate >= "2026-01-01"
  ).length,
  revokedThisMonth: accessReviews.filter(
    (r) => r.status === "Revoked" && r.lastReviewDate >= "2026-01-01"
  ).length,
  overdueReviews: accessReviews.filter((r) => r.status === "Expired" || r.status === "Pending").length,
};
