export interface CodeChange {
  id: string;
  title: string;
  description: string;
  type: "Feature" | "Bug Fix" | "Security Patch" | "Configuration" | "Infrastructure";
  status: "Pending Review" | "Approved" | "Deployed" | "Rejected" | "Rolled Back";
  riskLevel: "Low" | "Medium" | "High" | "Critical";
  author: string;
  reviewer: string | null;
  repository: string;
  pullRequestUrl: string;
  ticketId: string;
  createdDate: string;
  approvedDate: string | null;
  deployedDate: string | null;
  environment: "Development" | "Staging" | "Production";
  affectedSystems: string[];
  testsPassed: boolean;
  securityReview: boolean;
}

export const codeChanges: CodeChange[] = [
  {
    id: "CHG-001",
    title: "Implement user authentication flow",
    description: "Add OAuth 2.0 authentication with SSO support for enterprise clients",
    type: "Feature",
    status: "Deployed",
    riskLevel: "High",
    author: "Alex Thompson",
    reviewer: "Sarah Chen",
    repository: "acme/cloud-platform",
    pullRequestUrl: "https://github.com/acme/cloud-platform/pull/234",
    ticketId: "JIRA-1234",
    createdDate: "2024-01-10T09:00:00Z",
    approvedDate: "2024-01-12T14:30:00Z",
    deployedDate: "2024-01-13T10:00:00Z",
    environment: "Production",
    affectedSystems: ["Auth Service", "User Management", "API Gateway"],
    testsPassed: true,
    securityReview: true,
  },
  {
    id: "CHG-002",
    title: "Fix SQL injection vulnerability",
    description: "Patch critical SQL injection vulnerability in search endpoint",
    type: "Security Patch",
    status: "Deployed",
    riskLevel: "Critical",
    author: "Mike Johnson",
    reviewer: "Sarah Chen",
    repository: "acme/cloud-platform",
    pullRequestUrl: "https://github.com/acme/cloud-platform/pull/235",
    ticketId: "SEC-089",
    createdDate: "2024-01-14T08:00:00Z",
    approvedDate: "2024-01-14T10:00:00Z",
    deployedDate: "2024-01-14T11:30:00Z",
    environment: "Production",
    affectedSystems: ["Search Service", "Database Layer"],
    testsPassed: true,
    securityReview: true,
  },
  {
    id: "CHG-003",
    title: "Update database connection pooling",
    description: "Increase connection pool size and add timeout configurations",
    type: "Configuration",
    status: "Approved",
    riskLevel: "Medium",
    author: "Emily Davis",
    reviewer: "Alex Thompson",
    repository: "acme/infrastructure",
    pullRequestUrl: "https://github.com/acme/infrastructure/pull/89",
    ticketId: "OPS-456",
    createdDate: "2024-01-15T11:00:00Z",
    approvedDate: "2024-01-15T16:00:00Z",
    deployedDate: null,
    environment: "Staging",
    affectedSystems: ["Database", "API Services"],
    testsPassed: true,
    securityReview: false,
  },
  {
    id: "CHG-004",
    title: "Add rate limiting to public API",
    description: "Implement rate limiting middleware to prevent API abuse",
    type: "Feature",
    status: "Pending Review",
    riskLevel: "Medium",
    author: "Sarah Chen",
    reviewer: null,
    repository: "acme/cloud-platform",
    pullRequestUrl: "https://github.com/acme/cloud-platform/pull/240",
    ticketId: "JIRA-1289",
    createdDate: "2024-01-16T09:30:00Z",
    approvedDate: null,
    deployedDate: null,
    environment: "Development",
    affectedSystems: ["API Gateway", "Rate Limiter"],
    testsPassed: true,
    securityReview: false,
  },
  {
    id: "CHG-005",
    title: "Kubernetes cluster upgrade",
    description: "Upgrade Kubernetes from v1.27 to v1.28 with new security policies",
    type: "Infrastructure",
    status: "Pending Review",
    riskLevel: "High",
    author: "DevOps Team",
    reviewer: null,
    repository: "acme/k8s-configs",
    pullRequestUrl: "https://github.com/acme/k8s-configs/pull/156",
    ticketId: "OPS-501",
    createdDate: "2024-01-16T14:00:00Z",
    approvedDate: null,
    deployedDate: null,
    environment: "Staging",
    affectedSystems: ["All Services"],
    testsPassed: false,
    securityReview: false,
  },
  {
    id: "CHG-006",
    title: "Fix memory leak in background worker",
    description: "Resolve memory leak causing service degradation after 24hrs",
    type: "Bug Fix",
    status: "Deployed",
    riskLevel: "Medium",
    author: "Mike Johnson",
    reviewer: "Emily Davis",
    repository: "acme/cloud-platform",
    pullRequestUrl: "https://github.com/acme/cloud-platform/pull/238",
    ticketId: "BUG-234",
    createdDate: "2024-01-13T10:00:00Z",
    approvedDate: "2024-01-13T15:00:00Z",
    deployedDate: "2024-01-14T09:00:00Z",
    environment: "Production",
    affectedSystems: ["Background Workers", "Queue Service"],
    testsPassed: true,
    securityReview: false,
  },
  {
    id: "CHG-007",
    title: "Enable encryption at rest for S3 buckets",
    description: "Configure AES-256 encryption for all S3 storage buckets",
    type: "Security Patch",
    status: "Approved",
    riskLevel: "Low",
    author: "Alex Thompson",
    reviewer: "Sarah Chen",
    repository: "acme/infrastructure",
    pullRequestUrl: "https://github.com/acme/infrastructure/pull/92",
    ticketId: "SEC-091",
    createdDate: "2024-01-15T08:00:00Z",
    approvedDate: "2024-01-16T10:00:00Z",
    deployedDate: null,
    environment: "Production",
    affectedSystems: ["Storage Layer", "Backup Service"],
    testsPassed: true,
    securityReview: true,
  },
  {
    id: "CHG-008",
    title: "Rollback payment processor update",
    description: "Emergency rollback due to transaction failures",
    type: "Configuration",
    status: "Rolled Back",
    riskLevel: "Critical",
    author: "Emily Davis",
    reviewer: "Mike Johnson",
    repository: "acme/cloud-platform",
    pullRequestUrl: "https://github.com/acme/cloud-platform/pull/236",
    ticketId: "INC-078",
    createdDate: "2024-01-11T16:00:00Z",
    approvedDate: "2024-01-11T16:30:00Z",
    deployedDate: "2024-01-11T17:00:00Z",
    environment: "Production",
    affectedSystems: ["Payment Service", "Billing"],
    testsPassed: true,
    securityReview: false,
  },
];
