import { Control } from "@/types";

export const controls: Control[] = [
  {
    id: "CTL-001",
    name: "Multi-Factor Authentication",
    description: "All user accounts must use multi-factor authentication (MFA) for system access. This includes both internal employees and external contractors.",
    category: "Access Control",
    status: "Accepted",
    type: "Automated",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa", "iso27001"],
    evidenceIds: ["EV-001", "EV-002"],
    lastTested: "2026-01-30",
    nextReview: "2026-02-28",
    testFrequency: "Daily",
    implementationDetails: "Enforced via Okta with hardware tokens and authenticator apps as second factors.",
  },
  {
    id: "CTL-002",
    name: "Strong Password Policy",
    description: "Password requirements include minimum 12 characters, complexity requirements, and 90-day rotation.",
    category: "Access Control",
    status: "Accepted",
    type: "Automated",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa"],
    evidenceIds: ["EV-002"],
    lastTested: "2026-01-30",
    nextReview: "2026-02-28",
    testFrequency: "Daily",
    implementationDetails: "Enforced via Active Directory Group Policy and Okta password policies.",
  },
  {
    id: "CTL-003",
    name: "Access Control Policy",
    description: "Documented access control policy defining authorization requirements and access provisioning procedures.",
    category: "Access Control",
    status: "Accepted",
    type: "Manual",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    frameworkIds: ["soc2-type2", "hipaa", "iso27001", "gdpr"],
    evidenceIds: ["EV-003"],
    lastTested: "2026-01-15",
    nextReview: "2026-04-15",
    testFrequency: "Quarterly",
    implementationDetails: "Policy reviewed and approved by security team quarterly. Published in company wiki.",
  },
  {
    id: "CTL-009",
    name: "Data Encryption at Rest",
    description: "All sensitive data must be encrypted at rest using AES-256 encryption.",
    category: "Data Protection",
    status: "Accepted",
    type: "Automated",
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa", "gdpr"],
    evidenceIds: ["EV-005"],
    lastTested: "2026-01-28",
    nextReview: "2026-02-28",
    testFrequency: "Weekly",
    implementationDetails: "AWS KMS with customer-managed keys for all RDS and S3 resources.",
  },
  {
    id: "CTL-010",
    name: "Data Encryption in Transit",
    description: "All data in transit must be encrypted using TLS 1.2 or higher.",
    category: "Data Protection",
    status: "Accepted",
    type: "Automated",
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa", "gdpr"],
    evidenceIds: ["EV-006"],
    lastTested: "2026-01-28",
    nextReview: "2026-02-28",
    testFrequency: "Weekly",
    implementationDetails: "Enforced via AWS ALB, CloudFront, and API Gateway configurations.",
  },
  {
    id: "CTL-015",
    name: "Firewall Configuration",
    description: "Network firewalls configured to deny all traffic by default and only allow explicitly authorized traffic.",
    category: "Network Security",
    status: "Accepted",
    type: "Automated",
    owner: "Alex Johnson",
    ownerEmail: "alex.johnson@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa", "iso27001"],
    evidenceIds: ["EV-010"],
    lastTested: "2026-01-29",
    nextReview: "2026-02-28",
    testFrequency: "Weekly",
    implementationDetails: "AWS Security Groups and Network ACLs with Infrastructure as Code.",
  },
  {
    id: "CTL-020",
    name: "Security Monitoring",
    description: "Continuous security monitoring of all production systems with alerting on anomalies.",
    category: "Logging & Monitoring",
    status: "Accepted",
    type: "Automated",
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa"],
    evidenceIds: ["EV-014"],
    lastTested: "2026-01-31",
    nextReview: "2026-02-28",
    testFrequency: "Daily",
    implementationDetails: "Datadog APM and Security Monitoring with PagerDuty alerting.",
  },
  {
    id: "CTL-025",
    name: "Incident Response Plan",
    description: "Documented incident response procedures with defined roles and communication protocols.",
    category: "Incident Response",
    status: "Accepted",
    type: "Manual",
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    frameworkIds: ["soc2-type2", "hipaa", "gdpr"],
    evidenceIds: ["EV-022"],
    lastTested: "2026-01-10",
    nextReview: "2026-04-10",
    testFrequency: "Quarterly",
    implementationDetails: "Runbooks in Confluence with on-call rotation in PagerDuty.",
  },
  {
    id: "CTL-029",
    name: "Change Management Process",
    description: "All production changes must go through documented change management process with approvals.",
    category: "Change Management",
    status: "Needs Review",
    type: "Manual",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1"],
    evidenceIds: ["EV-025"],
    lastTested: "2026-01-20",
    nextReview: "2026-02-20",
    testFrequency: "Monthly",
    implementationDetails: "GitHub PR reviews with CODEOWNERS. Some emergency changes bypassed process.",
    failureReason: "3 emergency changes in January did not have proper approval documentation.",
  },
  {
    id: "CTL-033",
    name: "Vulnerability Scanning",
    description: "Regular vulnerability scanning of all systems with timely remediation of findings.",
    category: "Vulnerability Management",
    status: "Accepted",
    type: "Automated",
    owner: "Alex Johnson",
    ownerEmail: "alex.johnson@company.com",
    frameworkIds: ["soc2-type2", "soc2-type1", "hipaa", "iso27001"],
    evidenceIds: ["EV-019"],
    lastTested: "2026-01-30",
    nextReview: "2026-02-28",
    testFrequency: "Weekly",
    implementationDetails: "AWS Inspector and Snyk running in CI/CD pipeline.",
  },
  {
    id: "CTL-037",
    name: "Endpoint Protection",
    description: "All endpoints must have approved endpoint protection software installed and updated.",
    category: "Endpoint Security",
    status: "Additional Evidence Needed",
    type: "Automated",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    frameworkIds: ["soc2-type2", "hipaa", "iso27001"],
    evidenceIds: ["EV-027"],
    lastTested: "2026-01-31",
    nextReview: "2026-02-07",
    testFrequency: "Daily",
    implementationDetails: "CrowdStrike Falcon deployed via Jamf.",
    failureReason: "8 endpoints missing CrowdStrike agent - new hire laptops pending setup.",
  },
  {
    id: "CTL-040",
    name: "Business Continuity Plan",
    description: "Documented business continuity plan with recovery procedures and communication protocols.",
    category: "Business Continuity",
    status: "Accepted",
    type: "Manual",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    frameworkIds: ["soc2-type2", "hipaa", "iso27001"],
    evidenceIds: ["EV-032"],
    lastTested: "2025-12-15",
    nextReview: "2026-03-15",
    testFrequency: "Quarterly",
    implementationDetails: "Annual BCP review with tabletop exercises.",
  },
  {
    id: "CTL-041",
    name: "Backup and Recovery",
    description: "Regular backups of all critical systems with tested recovery procedures.",
    category: "Business Continuity",
    status: "Additional Evidence Needed",
    type: "Automated",
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    frameworkIds: ["soc2-type2", "hipaa"],
    evidenceIds: ["EV-032"],
    lastTested: "2026-01-29",
    nextReview: "2026-02-05",
    testFrequency: "Weekly",
    implementationDetails: "AWS Backup with cross-region replication.",
    failureReason: "Weekly backup restoration test failed - RDS snapshot restoration timeout.",
  },
  {
    id: "CTL-043",
    name: "Physical Access Controls",
    description: "Physical access to data centers and offices restricted to authorized personnel.",
    category: "Physical Security",
    status: "Accepted",
    type: "Manual",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    frameworkIds: ["soc2-type2", "hipaa"],
    evidenceIds: ["EV-028"],
    lastTested: "2026-01-25",
    nextReview: "2026-04-25",
    testFrequency: "Quarterly",
    implementationDetails: "Badge access with visitor logs. AWS handles data center physical security.",
  },
  {
    id: "CTL-045",
    name: "Security Awareness Training",
    description: "All employees must complete annual security awareness training.",
    category: "Human Resources",
    status: "Needs Review",
    type: "Manual",
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    frameworkIds: ["soc2-type2", "hipaa", "iso27001"],
    evidenceIds: ["EV-029"],
    lastTested: "2026-01-29",
    nextReview: "2026-02-28",
    testFrequency: "Monthly",
    implementationDetails: "KnowBe4 platform with quarterly phishing simulations.",
    failureReason: "12 employees have not completed 2026 annual training - due Feb 15.",
  },
  {
    id: "CTL-048",
    name: "Risk Assessment Process",
    description: "Regular risk assessments to identify and evaluate threats to information assets.",
    category: "Risk Management",
    status: "Accepted",
    type: "Manual",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    frameworkIds: ["soc2-type2", "hipaa", "iso27001", "gdpr"],
    evidenceIds: ["EV-033"],
    lastTested: "2026-01-15",
    nextReview: "2026-04-15",
    testFrequency: "Quarterly",
    implementationDetails: "Annual risk assessment with quarterly reviews using NIST framework.",
  },
];
