import { Evidence } from "@/types";

export const evidence: Evidence[] = [
  {
    id: "EV-001",
    name: "MFA Configuration Report",
    description: "Automated report showing MFA enforcement status for all user accounts from Okta",
    type: "Automated",
    status: "Current",
    controlIds: ["CTL-001", "CTL-002"],
    uploadedBy: "System",
    uploadedDate: "2026-01-30",
    expirationDate: null,
    fileSize: "245 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-002",
    name: "Password Policy Screenshot",
    description: "Screenshot of Active Directory password policy configuration",
    type: "Screenshot",
    status: "Current",
    controlIds: ["CTL-001", "CTL-002"],
    uploadedBy: "Sarah Chen",
    uploadedDate: "2026-01-15",
    expirationDate: "2026-04-15",
    fileSize: "1.2 MB",
    mimeType: "image/png",
  },
  {
    id: "EV-003",
    name: "Access Control Policy v3.2",
    description: "Current approved access control policy document",
    type: "Document",
    status: "Current",
    controlIds: ["CTL-003"],
    uploadedBy: "Michael Torres",
    uploadedDate: "2026-01-10",
    expirationDate: "2027-01-10",
    fileSize: "856 KB",
    mimeType: "application/pdf",
  },
  {
    id: "EV-005",
    name: "AWS KMS Encryption Report",
    description: "AWS Config report showing encryption status for all S3 buckets and RDS instances",
    type: "Automated",
    status: "Current",
    controlIds: ["CTL-009"],
    uploadedBy: "System",
    uploadedDate: "2026-01-28",
    expirationDate: null,
    fileSize: "128 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-006",
    name: "TLS Configuration Scan",
    description: "SSL Labs scan results for all public endpoints",
    type: "Automated",
    status: "Current",
    controlIds: ["CTL-010"],
    uploadedBy: "System",
    uploadedDate: "2026-01-28",
    expirationDate: null,
    fileSize: "89 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-010",
    name: "Security Group Configuration",
    description: "AWS Security Groups and Network ACL configuration export",
    type: "Automated",
    status: "Current",
    controlIds: ["CTL-015"],
    uploadedBy: "System",
    uploadedDate: "2026-01-29",
    expirationDate: null,
    fileSize: "456 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-014",
    name: "Datadog Monitoring Dashboard",
    description: "Screenshot of security monitoring dashboard configuration",
    type: "Screenshot",
    status: "Current",
    controlIds: ["CTL-020"],
    uploadedBy: "Jennifer Wu",
    uploadedDate: "2026-01-25",
    expirationDate: "2026-04-25",
    fileSize: "2.1 MB",
    mimeType: "image/png",
  },
  {
    id: "EV-019",
    name: "Vulnerability Scan Report Q4 2025",
    description: "Quarterly vulnerability assessment report from AWS Inspector and Snyk",
    type: "Report",
    status: "Current",
    controlIds: ["CTL-033"],
    uploadedBy: "Alex Johnson",
    uploadedDate: "2026-01-05",
    expirationDate: "2026-04-05",
    fileSize: "3.4 MB",
    mimeType: "application/pdf",
  },
  {
    id: "EV-022",
    name: "Incident Response Runbook",
    description: "Current incident response procedures and playbooks",
    type: "Document",
    status: "Current",
    controlIds: ["CTL-025"],
    uploadedBy: "Jennifer Wu",
    uploadedDate: "2025-12-15",
    expirationDate: "2026-12-15",
    fileSize: "1.8 MB",
    mimeType: "application/pdf",
  },
  {
    id: "EV-025",
    name: "Change Management Log January 2026",
    description: "Monthly log of all production changes with approval records",
    type: "Report",
    status: "Pending Review",
    controlIds: ["CTL-029"],
    uploadedBy: "Michael Torres",
    uploadedDate: "2026-01-31",
    expirationDate: "2026-02-28",
    fileSize: "567 KB",
    mimeType: "application/xlsx",
  },
  {
    id: "EV-027",
    name: "CrowdStrike Deployment Report",
    description: "Endpoint protection agent deployment status report",
    type: "Automated",
    status: "Expiring Soon",
    controlIds: ["CTL-037"],
    uploadedBy: "System",
    uploadedDate: "2026-01-15",
    expirationDate: "2026-02-15",
    fileSize: "234 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-028",
    name: "Physical Access Log Q4 2025",
    description: "Badge access and visitor logs for headquarters",
    type: "Report",
    status: "Current",
    controlIds: ["CTL-043"],
    uploadedBy: "Sarah Chen",
    uploadedDate: "2026-01-10",
    expirationDate: "2026-04-10",
    fileSize: "890 KB",
    mimeType: "application/pdf",
  },
  {
    id: "EV-029",
    name: "Security Training Completion Report",
    description: "KnowBe4 training completion status for all employees",
    type: "Automated",
    status: "Expiring Soon",
    controlIds: ["CTL-045"],
    uploadedBy: "System",
    uploadedDate: "2026-01-29",
    expirationDate: "2026-02-15",
    fileSize: "156 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-032",
    name: "Disaster Recovery Test Results",
    description: "Q4 2025 disaster recovery test execution results",
    type: "Report",
    status: "Expired",
    controlIds: ["CTL-040", "CTL-041"],
    uploadedBy: "David Kim",
    uploadedDate: "2025-10-20",
    expirationDate: "2026-01-20",
    fileSize: "2.3 MB",
    mimeType: "application/pdf",
  },
  {
    id: "EV-033",
    name: "Annual Risk Assessment 2025",
    description: "Comprehensive annual risk assessment using NIST framework",
    type: "Document",
    status: "Current",
    controlIds: ["CTL-048"],
    uploadedBy: "Michael Torres",
    uploadedDate: "2025-12-01",
    expirationDate: "2026-12-01",
    fileSize: "4.5 MB",
    mimeType: "application/pdf",
  },
  {
    id: "EV-034",
    name: "SSL Certificate Inventory",
    description: "Current SSL/TLS certificate inventory with expiration tracking",
    type: "Automated",
    status: "Current",
    controlIds: ["CTL-010"],
    uploadedBy: "System",
    uploadedDate: "2026-01-28",
    expirationDate: null,
    fileSize: "45 KB",
    mimeType: "application/json",
  },
  {
    id: "EV-035",
    name: "Vendor Security Assessments 2025",
    description: "Collection of vendor security questionnaires and assessments",
    type: "Document",
    status: "Pending Review",
    controlIds: [],
    uploadedBy: "Alex Johnson",
    uploadedDate: "2026-01-20",
    expirationDate: "2027-01-20",
    fileSize: "12.4 MB",
    mimeType: "application/zip",
  },
];
