import { Integration } from "@/types";

export const integrations: Integration[] = [
  {
    id: "INT-001",
    name: "Amazon Web Services",
    description: "Cloud infrastructure provider - monitors EC2, S3, IAM, and security configurations.",
    category: "Cloud Provider",
    status: "Connected",
    iconName: "aws",
    lastSyncDate: "2026-01-31T08:00:00Z",
    connectedDate: "2024-01-15",
    dataCollected: ["EC2 Instances", "S3 Buckets", "IAM Users", "Security Groups", "CloudTrail Logs"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-002",
    name: "Okta",
    description: "Identity provider - syncs user accounts, MFA status, and SSO configurations.",
    category: "Identity Provider",
    status: "Connected",
    iconName: "okta",
    lastSyncDate: "2026-01-31T07:30:00Z",
    connectedDate: "2024-01-20",
    dataCollected: ["User Accounts", "MFA Status", "SSO Apps", "Login Events"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-003",
    name: "GitHub",
    description: "Version control - monitors repositories, access controls, and security settings.",
    category: "Version Control",
    status: "Connected",
    iconName: "github",
    lastSyncDate: "2026-01-31T06:00:00Z",
    connectedDate: "2024-02-01",
    dataCollected: ["Repositories", "Team Members", "Branch Protection", "Security Alerts"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-004",
    name: "Slack",
    description: "Communication platform - monitors workspace settings and security configurations.",
    category: "Communication",
    status: "Connected",
    iconName: "slack",
    lastSyncDate: "2026-01-30T12:00:00Z",
    connectedDate: "2024-03-01",
    dataCollected: ["Workspace Members", "App Integrations", "Security Settings"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-005",
    name: "Jira",
    description: "Project management - tracks security-related tickets and compliance tasks.",
    category: "Project Management",
    status: "Connected",
    iconName: "jira",
    lastSyncDate: "2026-01-31T09:00:00Z",
    connectedDate: "2024-03-15",
    dataCollected: ["Security Issues", "Compliance Tasks", "Project Status"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-006",
    name: "Rippling",
    description: "HR platform - syncs employee data, onboarding status, and training completion.",
    category: "HR",
    status: "Connected",
    iconName: "rippling",
    lastSyncDate: "2026-01-31T00:00:00Z",
    connectedDate: "2024-04-01",
    dataCollected: ["Employees", "Departments", "Training Status", "Offboarding"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-007",
    name: "Jamf",
    description: "MDM platform - monitors macOS device compliance and security configurations.",
    category: "MDM",
    status: "Connected",
    iconName: "jamf",
    lastSyncDate: "2026-01-31T08:30:00Z",
    connectedDate: "2024-05-01",
    dataCollected: ["Devices", "OS Versions", "Security Settings", "App Inventory"],
    healthStatus: "Degraded",
  },
  {
    id: "INT-008",
    name: "CrowdStrike",
    description: "EDR platform - monitors endpoint protection status and threat detections.",
    category: "Security",
    status: "Connected",
    iconName: "crowdstrike",
    lastSyncDate: "2026-01-31T09:15:00Z",
    connectedDate: "2024-06-01",
    dataCollected: ["Protected Endpoints", "Threat Detections", "Agent Status"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-009",
    name: "Google Workspace",
    description: "Cloud productivity suite - monitors user accounts and security settings.",
    category: "Cloud Provider",
    status: "Available",
    iconName: "google",
    lastSyncDate: null,
    connectedDate: null,
    dataCollected: ["Users", "Groups", "Drive Files", "Security Settings"],
    healthStatus: "N/A",
  },
  {
    id: "INT-010",
    name: "Microsoft 365",
    description: "Cloud productivity suite - monitors Azure AD, Exchange, and security configurations.",
    category: "Cloud Provider",
    status: "Available",
    iconName: "microsoft",
    lastSyncDate: null,
    connectedDate: null,
    dataCollected: ["Azure AD Users", "Exchange Settings", "Compliance Policies"],
    healthStatus: "N/A",
  },
  {
    id: "INT-011",
    name: "Datadog",
    description: "Monitoring platform - syncs security alerts and compliance dashboards.",
    category: "Security",
    status: "Syncing",
    iconName: "datadog",
    lastSyncDate: "2026-01-31T09:25:00Z",
    connectedDate: "2024-07-01",
    dataCollected: ["Security Signals", "Audit Logs", "Dashboards"],
    healthStatus: "Healthy",
  },
  {
    id: "INT-012",
    name: "Snyk",
    description: "Security scanning - monitors code vulnerabilities and dependency issues.",
    category: "Security",
    status: "Error",
    iconName: "snyk",
    lastSyncDate: "2026-01-29T15:00:00Z",
    connectedDate: "2024-08-01",
    dataCollected: ["Vulnerabilities", "Dependencies", "License Issues"],
    healthStatus: "Down",
  },
];
