import { Person } from "@/types";

export const people: Person[] = [
  {
    id: "PER-001",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    department: "Security",
    role: "Security Manager",
    startDate: "2022-03-15",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-10",
    trainingDueDate: "2027-01-10",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-002",
    name: "Michael Torres",
    email: "michael.torres@company.com",
    department: "Compliance",
    role: "Compliance Director",
    startDate: "2021-06-01",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-08",
    trainingDueDate: "2027-01-08",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-003",
    name: "Jennifer Wu",
    email: "jennifer.wu@company.com",
    department: "Security",
    role: "Security Analyst",
    startDate: "2023-01-10",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-12",
    trainingDueDate: "2027-01-12",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-004",
    name: "David Kim",
    email: "david.kim@company.com",
    department: "Engineering",
    role: "Senior DevOps Engineer",
    startDate: "2022-08-20",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-15",
    trainingDueDate: "2027-01-15",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-005",
    name: "Alex Johnson",
    email: "alex.johnson@company.com",
    department: "Engineering",
    role: "Infrastructure Engineer",
    startDate: "2023-05-01",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-20",
    trainingDueDate: "2027-01-20",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-006",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@company.com",
    department: "Engineering",
    role: "Software Engineer",
    startDate: "2024-02-01",
    trainingStatus: "In Progress",
    trainingCompletionDate: null,
    trainingDueDate: "2026-02-15",
    accessReviewStatus: "Pending",
    lastAccessReview: null,
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-007",
    name: "Marcus Thompson",
    email: "marcus.thompson@company.com",
    department: "Sales",
    role: "Account Executive",
    startDate: "2024-06-15",
    trainingStatus: "Overdue",
    trainingCompletionDate: null,
    trainingDueDate: "2026-01-15",
    accessReviewStatus: "Overdue",
    lastAccessReview: "2025-06-20",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-008",
    name: "Lisa Park",
    email: "lisa.park@company.com",
    department: "Product",
    role: "Product Manager",
    startDate: "2023-09-01",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-05",
    trainingDueDate: "2027-01-05",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-009",
    name: "James Wilson",
    email: "james.wilson@company.com",
    department: "Engineering",
    role: "Backend Developer",
    startDate: "2025-01-15",
    trainingStatus: "Not Started",
    trainingCompletionDate: null,
    trainingDueDate: "2026-02-15",
    accessReviewStatus: "Pending",
    lastAccessReview: null,
    backgroundCheckStatus: "In Progress",
    mfaEnabled: false,
  },
  {
    id: "PER-010",
    name: "Amanda Foster",
    email: "amanda.foster@company.com",
    department: "HR",
    role: "HR Manager",
    startDate: "2022-11-01",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-18",
    trainingDueDate: "2027-01-18",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-011",
    name: "Robert Chen",
    email: "robert.chen@company.com",
    department: "Finance",
    role: "Financial Analyst",
    startDate: "2024-04-01",
    trainingStatus: "Complete",
    trainingCompletionDate: "2026-01-22",
    trainingDueDate: "2027-01-22",
    accessReviewStatus: "Pending",
    lastAccessReview: "2025-07-01",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
  {
    id: "PER-012",
    name: "Nicole Adams",
    email: "nicole.adams@company.com",
    department: "Marketing",
    role: "Marketing Manager",
    startDate: "2023-07-15",
    trainingStatus: "Overdue",
    trainingCompletionDate: null,
    trainingDueDate: "2026-01-20",
    accessReviewStatus: "Reviewed",
    lastAccessReview: "2026-01-05",
    backgroundCheckStatus: "Cleared",
    mfaEnabled: true,
  },
];
