import { Policy } from "@/types";

export const policies: Policy[] = [
  {
    id: "POL-001",
    name: "Information Security Policy",
    description: "Overarching policy defining the organization's approach to information security, roles and responsibilities, and risk management framework.",
    status: "Approved",
    version: "3.2",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    department: "Security",
    approvedDate: "2025-12-01",
    nextReviewDate: "2026-12-01",
    lastUpdated: "2025-12-01",
    frameworkIds: ["soc2-type2", "iso27001", "hipaa"],
  },
  {
    id: "POL-002",
    name: "Access Control Policy",
    description: "Defines requirements for user authentication, authorization, access provisioning, and access review procedures.",
    status: "Approved",
    version: "2.5",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    department: "Security",
    approvedDate: "2026-01-10",
    nextReviewDate: "2026-04-10",
    lastUpdated: "2026-01-10",
    frameworkIds: ["soc2-type2", "hipaa", "gdpr"],
  },
  {
    id: "POL-003",
    name: "Data Classification Policy",
    description: "Establishes data classification levels (Public, Internal, Confidential, Restricted) and handling requirements for each.",
    status: "Approved",
    version: "2.0",
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    department: "Compliance",
    approvedDate: "2025-10-15",
    nextReviewDate: "2026-10-15",
    lastUpdated: "2025-10-15",
    frameworkIds: ["soc2-type2", "iso27001", "gdpr"],
  },
  {
    id: "POL-004",
    name: "Acceptable Use Policy",
    description: "Guidelines for acceptable use of company IT resources, including devices, email, internet, and software.",
    status: "Approved",
    version: "4.1",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    department: "IT",
    approvedDate: "2025-11-20",
    nextReviewDate: "2026-11-20",
    lastUpdated: "2025-11-20",
    frameworkIds: ["soc2-type2"],
  },
  {
    id: "POL-005",
    name: "Incident Response Policy",
    description: "Procedures for identifying, responding to, and recovering from security incidents. Includes escalation paths and communication protocols.",
    status: "Approved",
    version: "3.0",
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    department: "Security",
    approvedDate: "2025-12-15",
    nextReviewDate: "2026-12-15",
    lastUpdated: "2025-12-15",
    frameworkIds: ["soc2-type2", "hipaa", "gdpr"],
  },
  {
    id: "POL-006",
    name: "Data Retention Policy",
    description: "Defines retention periods for different data categories and secure disposal requirements.",
    status: "Approved",
    version: "2.1",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    department: "Compliance",
    approvedDate: "2026-01-30",
    nextReviewDate: "2027-01-30",
    lastUpdated: "2026-01-30",
    frameworkIds: ["gdpr", "hipaa"],
  },
  {
    id: "POL-007",
    name: "Vendor Management Policy",
    description: "Requirements for vendor selection, security assessment, ongoing monitoring, and contract management.",
    status: "In Review",
    version: "1.3",
    owner: "Alex Johnson",
    ownerEmail: "alex.johnson@company.com",
    department: "Security",
    approvedDate: null,
    nextReviewDate: "2026-02-15",
    lastUpdated: "2026-01-25",
    frameworkIds: ["soc2-type2", "hipaa"],
  },
  {
    id: "POL-008",
    name: "Change Management Policy",
    description: "Procedures for requesting, reviewing, approving, and implementing changes to production systems.",
    status: "Needs Update",
    version: "2.4",
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    department: "Engineering",
    approvedDate: "2025-06-01",
    nextReviewDate: "2026-01-15",
    lastUpdated: "2025-06-01",
    frameworkIds: ["soc2-type2", "soc2-type1"],
  },
  {
    id: "POL-009",
    name: "Business Continuity Policy",
    description: "Framework for maintaining operations during disruptions, including disaster recovery and business continuity planning.",
    status: "Approved",
    version: "2.2",
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    department: "Operations",
    approvedDate: "2025-09-01",
    nextReviewDate: "2026-09-01",
    lastUpdated: "2025-09-01",
    frameworkIds: ["soc2-type2", "hipaa", "iso27001"],
  },
  {
    id: "POL-010",
    name: "Remote Work Security Policy",
    description: "Security requirements for employees working remotely, including VPN usage, device security, and physical workspace requirements.",
    status: "Approved",
    version: "1.5",
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    department: "Security",
    approvedDate: "2025-08-15",
    nextReviewDate: "2026-08-15",
    lastUpdated: "2025-08-15",
    frameworkIds: ["soc2-type2"],
  },
  {
    id: "POL-011",
    name: "Privacy Policy",
    description: "Customer-facing privacy policy describing data collection, use, sharing, and individual rights.",
    status: "Approved",
    version: "5.0",
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    department: "Legal",
    approvedDate: "2025-11-01",
    nextReviewDate: "2026-11-01",
    lastUpdated: "2025-11-01",
    frameworkIds: ["gdpr", "hipaa"],
  },
  {
    id: "POL-012",
    name: "Cryptographic Controls Policy",
    description: "Requirements for encryption, key management, certificate handling, and cryptographic algorithm selection.",
    status: "Draft",
    version: "1.0",
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    department: "Security",
    approvedDate: null,
    nextReviewDate: "2026-03-01",
    lastUpdated: "2026-01-20",
    frameworkIds: ["iso27001", "soc2-type2"],
  },
];
