import { Risk } from "@/types";

export const risks: Risk[] = [
  {
    id: "RSK-001",
    title: "Third-Party Vendor Data Breach",
    description: "Risk of data breach through compromised third-party vendor with access to customer data. Payment processor and analytics providers have direct API access.",
    category: "Operational",
    severity: "Critical",
    status: "In Treatment",
    likelihood: 3,
    impact: 5,
    riskScore: 15,
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    treatmentPlan: "Implement vendor security assessment program, require SOC 2 attestation, add DLP monitoring on API connections",
    mitigatingControls: ["CTL-048"],
    dateIdentified: "2025-11-15",
    dueDate: "2026-03-01",
    lastReviewed: "2026-01-20",
    residualRisk: "High",
  },
  {
    id: "RSK-002",
    title: "Ransomware Attack",
    description: "Risk of ransomware infection leading to data encryption and business disruption. Remote work increases exposure through personal devices.",
    category: "Technical",
    severity: "Critical",
    status: "In Treatment",
    likelihood: 3,
    impact: 5,
    riskScore: 15,
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    treatmentPlan: "Deploy EDR solution, implement network segmentation, enhance backup strategy with air-gapped copies",
    mitigatingControls: ["CTL-037", "CTL-041", "CTL-015"],
    dateIdentified: "2025-10-01",
    dueDate: "2026-02-15",
    lastReviewed: "2026-01-25",
    residualRisk: "Medium",
  },
  {
    id: "RSK-003",
    title: "Insider Threat - Data Exfiltration",
    description: "Risk of malicious or negligent insider exfiltrating sensitive customer or company data before termination or during employment.",
    category: "Operational",
    severity: "High",
    status: "Open",
    likelihood: 2,
    impact: 5,
    riskScore: 10,
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    treatmentPlan: "Implement DLP solution, enhance access logging, establish offboarding procedures with immediate access revocation",
    mitigatingControls: ["CTL-003", "CTL-020"],
    dateIdentified: "2025-12-01",
    dueDate: "2026-04-01",
    lastReviewed: "2026-01-15",
    residualRisk: "Medium",
  },
  {
    id: "RSK-004",
    title: "Cloud Misconfiguration",
    description: "Risk of data exposure through misconfigured cloud storage buckets, security groups, or IAM policies in AWS environment.",
    category: "Technical",
    severity: "High",
    status: "Mitigated",
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    treatmentPlan: "Implement AWS Config rules, deploy CSPM tool, require infrastructure as code for all changes",
    mitigatingControls: ["CTL-015", "CTL-029", "CTL-033"],
    dateIdentified: "2025-08-15",
    dueDate: "2025-12-01",
    lastReviewed: "2026-01-28",
    residualRisk: "Low",
  },
  {
    id: "RSK-005",
    title: "Regulatory Non-Compliance (SOC 2)",
    description: "Risk of failing SOC 2 Type II audit due to control gaps, impacting customer trust and contract renewals.",
    category: "Compliance",
    severity: "High",
    status: "In Treatment",
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    treatmentPlan: "Complete control remediation, gather evidence, conduct internal audit before external assessment",
    mitigatingControls: ["CTL-029", "CTL-045"],
    dateIdentified: "2025-09-01",
    dueDate: "2026-03-15",
    lastReviewed: "2026-01-30",
    residualRisk: "Low",
  },
  {
    id: "RSK-006",
    title: "API Security Vulnerability",
    description: "Risk of unauthorized access through API vulnerabilities including broken authentication, injection attacks, or excessive data exposure.",
    category: "Technical",
    severity: "High",
    status: "Mitigated",
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    owner: "Alex Johnson",
    ownerEmail: "alex.johnson@company.com",
    treatmentPlan: "Implement API gateway with rate limiting, add OWASP ZAP to CI/CD, conduct API penetration testing",
    mitigatingControls: ["CTL-033", "CTL-015"],
    dateIdentified: "2025-10-15",
    dueDate: "2026-01-15",
    lastReviewed: "2026-01-20",
    residualRisk: "Low",
  },
  {
    id: "RSK-007",
    title: "Business Continuity - Key Person Dependency",
    description: "Risk of operational disruption if key technical personnel become unavailable. Single points of failure in infrastructure management.",
    category: "Operational",
    severity: "Medium",
    status: "Open",
    likelihood: 3,
    impact: 3,
    riskScore: 9,
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    treatmentPlan: "Document critical procedures, cross-train team members, establish on-call rotation",
    mitigatingControls: ["CTL-040"],
    dateIdentified: "2025-11-01",
    dueDate: "2026-05-01",
    lastReviewed: "2026-01-10",
  },
  {
    id: "RSK-008",
    title: "Phishing Attack",
    description: "Risk of successful phishing attack leading to credential compromise and unauthorized system access.",
    category: "Operational",
    severity: "Medium",
    status: "In Treatment",
    likelihood: 4,
    impact: 2,
    riskScore: 8,
    owner: "Sarah Chen",
    ownerEmail: "sarah.chen@company.com",
    treatmentPlan: "Enhance email filtering, conduct regular phishing simulations, improve security awareness training",
    mitigatingControls: ["CTL-001", "CTL-045"],
    dateIdentified: "2025-07-01",
    dueDate: "2026-02-28",
    lastReviewed: "2026-01-29",
    residualRisk: "Low",
  },
  {
    id: "RSK-009",
    title: "Data Center Outage",
    description: "Risk of service disruption due to primary AWS region outage affecting customer-facing applications.",
    category: "Technical",
    severity: "Medium",
    status: "Mitigated",
    likelihood: 1,
    impact: 4,
    riskScore: 4,
    owner: "David Kim",
    ownerEmail: "david.kim@company.com",
    treatmentPlan: "Implement multi-region architecture, configure automatic failover, test DR procedures quarterly",
    mitigatingControls: ["CTL-040", "CTL-041"],
    dateIdentified: "2025-06-01",
    dueDate: "2025-09-01",
    lastReviewed: "2026-01-15",
    residualRisk: "Low",
  },
  {
    id: "RSK-010",
    title: "GDPR Data Subject Request Failure",
    description: "Risk of inability to fulfill data subject requests within required timeframes, leading to regulatory fines.",
    category: "Compliance",
    severity: "Medium",
    status: "Open",
    likelihood: 2,
    impact: 3,
    riskScore: 6,
    owner: "Michael Torres",
    ownerEmail: "michael.torres@company.com",
    treatmentPlan: "Implement data discovery tool, establish DSR handling procedures, train customer support team",
    mitigatingControls: [],
    dateIdentified: "2025-12-15",
    dueDate: "2026-06-01",
    lastReviewed: "2026-01-05",
  },
  {
    id: "RSK-011",
    title: "Software Supply Chain Attack",
    description: "Risk of compromised dependencies or development tools introducing malicious code into production systems.",
    category: "Technical",
    severity: "High",
    status: "In Treatment",
    likelihood: 2,
    impact: 4,
    riskScore: 8,
    owner: "Alex Johnson",
    ownerEmail: "alex.johnson@company.com",
    treatmentPlan: "Implement SCA scanning, pin dependency versions, establish software bill of materials",
    mitigatingControls: ["CTL-033", "CTL-029"],
    dateIdentified: "2025-11-20",
    dueDate: "2026-03-01",
    lastReviewed: "2026-01-25",
    residualRisk: "Medium",
  },
  {
    id: "RSK-012",
    title: "Reputational Damage from Security Incident",
    description: "Risk of customer loss and brand damage following a publicized security incident or data breach.",
    category: "Reputational",
    severity: "Low",
    status: "Accepted",
    likelihood: 1,
    impact: 4,
    riskScore: 4,
    owner: "Jennifer Wu",
    ownerEmail: "jennifer.wu@company.com",
    treatmentPlan: "Accepted risk with incident response and communication plan in place. PR team briefed on response procedures.",
    mitigatingControls: ["CTL-025", "CTL-027"],
    dateIdentified: "2025-08-01",
    dueDate: "2025-10-01",
    lastReviewed: "2026-01-01",
  },
];
