import { Vendor } from "@/types";

export const vendors: Vendor[] = [
  {
    id: "VND-001",
    name: "Amazon Web Services",
    category: "Cloud Infrastructure",
    riskRating: "High",
    status: "Approved",
    dataAccess: ["Customer Data", "System Logs", "Application Data"],
    complianceCertifications: ["SOC 2 Type II", "ISO 27001", "HIPAA BAA", "FedRAMP"],
    contactName: "AWS Enterprise Support",
    contactEmail: "enterprise@aws.com",
    contractStartDate: "2024-01-01",
    contractEndDate: "2027-01-01",
    lastAssessmentDate: "2025-12-01",
    nextReviewDate: "2026-12-01",
    description: "Primary cloud infrastructure provider hosting all production workloads.",
  },
  {
    id: "VND-002",
    name: "Okta",
    category: "Security",
    riskRating: "High",
    status: "Approved",
    dataAccess: ["User Identities", "Authentication Logs", "Access Policies"],
    complianceCertifications: ["SOC 2 Type II", "ISO 27001", "FedRAMP"],
    contactName: "Okta Support",
    contactEmail: "support@okta.com",
    contractStartDate: "2024-06-01",
    contractEndDate: "2026-06-01",
    lastAssessmentDate: "2025-11-15",
    nextReviewDate: "2026-05-01",
    description: "Identity and access management platform for SSO and MFA.",
  },
  {
    id: "VND-003",
    name: "Datadog",
    category: "Security",
    riskRating: "Medium",
    status: "Approved",
    dataAccess: ["System Metrics", "Application Logs", "Infrastructure Data"],
    complianceCertifications: ["SOC 2 Type II", "ISO 27001"],
    contactName: "Datadog Sales",
    contactEmail: "sales@datadog.com",
    contractStartDate: "2024-03-01",
    contractEndDate: "2026-03-01",
    lastAssessmentDate: "2026-01-15",
    nextReviewDate: "2027-01-15",
    description: "Monitoring, logging, and security observability platform.",
  },
  {
    id: "VND-004",
    name: "Stripe",
    category: "Payment Processing",
    riskRating: "Critical",
    status: "Approved",
    dataAccess: ["Payment Data", "Customer Billing Info"],
    complianceCertifications: ["PCI DSS Level 1", "SOC 2 Type II", "ISO 27001"],
    contactName: "Stripe Support",
    contactEmail: "support@stripe.com",
    contractStartDate: "2023-01-01",
    contractEndDate: "2026-01-01",
    lastAssessmentDate: "2025-10-01",
    nextReviewDate: "2026-01-31",
    description: "Payment processing and billing platform for customer transactions.",
  },
  {
    id: "VND-005",
    name: "Slack",
    category: "SaaS Application",
    riskRating: "Medium",
    status: "Approved",
    dataAccess: ["Internal Communications", "File Sharing"],
    complianceCertifications: ["SOC 2 Type II", "ISO 27001"],
    contactName: "Slack Enterprise",
    contactEmail: "enterprise@slack.com",
    contractStartDate: "2024-01-01",
    contractEndDate: "2026-01-01",
    lastAssessmentDate: "2025-09-01",
    nextReviewDate: "2026-09-01",
    description: "Team communication and collaboration platform.",
  },
  {
    id: "VND-006",
    name: "GitHub",
    category: "SaaS Application",
    riskRating: "High",
    status: "Approved",
    dataAccess: ["Source Code", "CI/CD Pipelines", "Developer Activity"],
    complianceCertifications: ["SOC 2 Type II"],
    contactName: "GitHub Enterprise",
    contactEmail: "enterprise@github.com",
    contractStartDate: "2023-06-01",
    contractEndDate: "2026-06-01",
    lastAssessmentDate: "2025-11-01",
    nextReviewDate: "2026-11-01",
    description: "Source code repository and CI/CD platform.",
  },
  {
    id: "VND-007",
    name: "Rippling",
    category: "HR & Payroll",
    riskRating: "High",
    status: "Approved",
    dataAccess: ["Employee PII", "Payroll Data", "Benefits Information"],
    complianceCertifications: ["SOC 2 Type II"],
    contactName: "Rippling Support",
    contactEmail: "support@rippling.com",
    contractStartDate: "2024-01-01",
    contractEndDate: "2027-01-01",
    lastAssessmentDate: "2025-12-15",
    nextReviewDate: "2026-12-15",
    description: "HR, payroll, and IT management platform.",
  },
  {
    id: "VND-008",
    name: "CrowdStrike",
    category: "Security",
    riskRating: "Medium",
    status: "Approved",
    dataAccess: ["Endpoint Telemetry", "Threat Intelligence", "Device Inventory"],
    complianceCertifications: ["SOC 2 Type II", "FedRAMP"],
    contactName: "CrowdStrike Support",
    contactEmail: "support@crowdstrike.com",
    contractStartDate: "2024-09-01",
    contractEndDate: "2026-09-01",
    lastAssessmentDate: "2025-08-15",
    nextReviewDate: "2026-08-15",
    description: "Endpoint detection and response (EDR) security platform.",
  },
  {
    id: "VND-009",
    name: "Snowflake",
    category: "Data Processor",
    riskRating: "High",
    status: "Under Review",
    dataAccess: ["Analytics Data", "Business Intelligence"],
    complianceCertifications: ["SOC 2 Type II", "ISO 27001", "HIPAA"],
    contactName: "Snowflake Sales",
    contactEmail: "sales@snowflake.com",
    contractStartDate: "2025-01-01",
    contractEndDate: "2028-01-01",
    lastAssessmentDate: "2026-01-10",
    nextReviewDate: "2026-02-15",
    description: "Cloud data warehouse for analytics and reporting.",
  },
  {
    id: "VND-010",
    name: "Segment",
    category: "Data Processor",
    riskRating: "Medium",
    status: "Pending",
    dataAccess: ["User Analytics", "Event Data"],
    complianceCertifications: ["SOC 2 Type II"],
    contactName: "Segment Sales",
    contactEmail: "sales@segment.com",
    contractStartDate: "",
    contractEndDate: "",
    lastAssessmentDate: "2026-01-25",
    nextReviewDate: "2026-03-01",
    description: "Customer data platform for analytics integration.",
  },
];
